#!/bin/bash
echo "📊 LIFE FEEL - PROJECT STATUS"
echo "=============================="
echo "✅ Services running:"
echo "   - API Gateway: http://localhost:4000"
echo "   - Auth Service: http://localhost:4001"
echo ""
echo "✅ Working endpoints:"
echo "   - GET http://localhost:4000/health"
echo "   - GET http://localhost:4000/api/v1/test"
echo "   - GET http://localhost:4001/health"
echo "   - GET http://localhost:4001/api/v1/auth/test"
echo ""
echo "📁 Repo: cofiemorridev/lifefeel (main)"
echo "🚀 Next: Day 3 - Database integration & real auth"
